apiVersion: v1
kind: Namespace
metadata:
  name: dell-fw-update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dell-fw-update 
  namespace: dell-fw-update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dell-fw-update
  namespace: dell-fw-update
subjects:
- kind: ServiceAccount 
  name: dell-fw-update
  namespace: dell-fw-update
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dell-fw-update
  namespace: dell-fw-update
spec:
  selector:
    matchLabels:
      name: dell-fw-update
  template:
    metadata:
      labels:
        name: dell-fw-update
    spec:
      nodeSelector:
        platform/baremetal: dell 
      containers:
      - image: quay.io/dphillip/dell-dsu:latest 
        imagePullPolicy: Always
        name: dell-fw-update 
        terminationMessagePath: /dev/termination-log
        securityContext:
          privileged: true
      hostNetwork: true
      hostPID: true
      serviceAccountName: dell-fw-update
      terminationGracePeriodSeconds: 10
